name: project
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.8.0
  flutter_secure_storage: ^9.2.2
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  flutter_image_compress: ^2.3.0
  uuid: ^4.5.1
  flutter_stripe: ^11.5.0
  url_launcher: ^6.3.1
  firebase_core: ^3.13.1
  firebase_messaging: ^15.2.5
  flutter_local_notifications: ^18.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  patrol: ^4.3.0
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

patrol:
  app_name: project
  android:
    package_name: com.example.project